# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenColorIO Project.

version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    # Only do security updates rather than all version updates.
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "quarterly"
    # Only do security updates rather than all version updates.
    open-pull-requests-limit: 0
