# azure-pipelines template file
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

parameters:
  buildType: Release
  cxxCompiler: ''
  cCompiler: ''
  cmakeOpts: ''

steps:
- bash: |
    if [ "$CXXCOMPILER" ]; then
        export CXX="$CXXCOMPILER"
    fi

    if [ "$CCOMPILER" ]; then
        export CC="$CCOMPILER"
    fi

    cmake --build . \
          --target install \
          --config ${{ parameters.buildType }} \
          ${{ parameters.cmakeOpts }}
  workingDirectory: _build
  displayName: Build OCIO

- template: test.yml
