/*
Copyright (c) 2003-2010 Sony Pictures Imageworks Inc., et al.
All Rights Reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
* Neither the name of Sony Pictures Imageworks nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <OpenColorSpace/OpenColorSpace.h>

#include "Processor.h"
#include "ScanlineHelper.h"

#include <sstream>

OCS_NAMESPACE_ENTER
{
    Processor::~Processor()
    { }
    
    
    //////////////////////////////////////////////////////////////////////////
    
    ConstProcessorRcPtr LocalProcessor::Create(const OpRcPtrVec& opVec)
    {
        return ConstProcessorRcPtr(new LocalProcessor(opVec), &deleter);
    }
    
    void LocalProcessor::deleter(LocalProcessor* p)
    {
        delete p;
    }
    
    LocalProcessor::LocalProcessor(const OpRcPtrVec& opVec):
        m_opVec(opVec)
    { }
    
    LocalProcessor::~LocalProcessor()
    { }
    
    bool LocalProcessor::isNoOp() const
    {
        return m_opVec.empty();
    }
    
    void LocalProcessor::apply(ImageDesc& img) const
    {
        if(m_opVec.empty()) return;
        
        ScanlineHelper scanlineHelper(img);
        float * rgbaBuffer = 0;
        long numPixels = 0;
        
        while(true)
        {
            scanlineHelper.prepRGBAScanline(&rgbaBuffer, &numPixels);
            if(numPixels == 0) break;
            if(!rgbaBuffer)
                throw OCSException("Cannot apply transform; null image.");
            
            for(unsigned int i=0; i<m_opVec.size(); ++i)
            {
                m_opVec[i]->apply(rgbaBuffer, numPixels);
            }
            
            scanlineHelper.finishRGBAScanline();
        }
    }
    
    void LocalProcessor::applyRGB(float * pixel) const
    {
        if(m_opVec.empty()) return;
        
        // We need to allocate a temp array as the pixel must be 4 floats in size.
        
        float rgbaBuffer[4] = { pixel[0], pixel[1], pixel[2], 0.0f };
        
        for(unsigned int i=0; i<m_opVec.size(); ++i)
        {
            m_opVec[i]->apply(rgbaBuffer, 1);
        }
        
        pixel[0] = rgbaBuffer[0];
        pixel[1] = rgbaBuffer[1];
        pixel[2] = rgbaBuffer[2];
    }
    
    
    
    
    ///////////////////////////////////////////////////////////////////////////
    
    
    void WriteShaderHeader(std::ostringstream* shader, const std::string & pixelName,
                           const GpuShaderDesc & gpuDesc)
    {
        if(!shader) return;
        
        *shader << "\n// Generated by OpenColorSpace" << "\n";
        *shader << "\n";
        
        GpuLanguage lang = gpuDesc.getLanguage();
        
        std::string fcnName = gpuDesc.getFunctionName();
        
        if(lang == GPU_LANGUAGE_CG)
        {
            *shader << "half4 " << fcnName << "(in half4 inPixel," << "\n";
        }
        else if(lang == GPU_LANGUAGE_GLSL)
        {
            *shader << "vec4 " << fcnName << "(in vec4 inPixel," << "\n";
        }
        else throw OCSException("Unspecified shader language.");
        
        *shader << "    const uniform sampler3D lut3d)" << "\n";
        *shader << "{" << "\n";
        
        if(lang == GPU_LANGUAGE_CG)
        {
            *shader << "    half4 " << pixelName << " = inPixel;" << "\n";
        }
        else if(lang == GPU_LANGUAGE_GLSL)
        {
            *shader << "    vec4 " << pixelName << " = inPixel;" << "\n";
        }
        else throw OCSException("Unspecified shader language.");
    }
    
    
    void WriteShaderFooter(std::ostringstream* shader,
                           const std::string & pixelName,
                           const GpuShaderDesc & /*gpuDesc*/)
    {
        *shader << "    return " << pixelName << ";\n";
        *shader << "}" << "\n";
        *shader << "\n";
    }
    
    void LocalProcessor::computeGPU(std::ostringstream * shader,
                                    std::ostringstream * lut3dCacheID, float * lut3d,
                                    const GpuShaderDesc & gpuDesc) const
    {
        std::string pixelName = "out_pixel";
        WriteShaderHeader(shader, pixelName, gpuDesc);
        
        //bool writeToShader = false;
        /*
        for(unsigned int i=0; i<m_opVec.size(); ++i)
        {
            if(m_opVec[i]->supportsGPU())
            {
                m_opVec[i]->computeGPU(shader, pixelName, lut3dCacheID, lut3d, gpuDesc);
            }
        }
        */
        
        WriteShaderFooter(shader, pixelName, gpuDesc);
    }
    
    const char * LocalProcessor::getGPUShaderText(const GpuShaderDesc & gpuDesc) const
    {
        std::ostringstream shader;
        computeGPU(&shader, 0, 0, gpuDesc);
        
        // TODO: This is not multi-thread safe. Cache result? or mutex?
        m_shaderText = shader.str();
        return m_shaderText.c_str();
    }
    
    /*
    int LocalProcessor::getGPULut3DEdgeSize() const
    {
        return 0;
    }
    
    const char * LocalProcessor::getGPULut3DCacheID(const GpuProfileDesc & gpuDesc) const
    {
        return "";
    }
    
    void LocalProcessor::getGPULut3D(float* lut3d, const GpuProfileDesc & gpuDesc) const
    {
        
    }
    */
}
OCS_NAMESPACE_EXIT
