.\"Shiju P. Nair September 30, 2004
.TH JPEGICC 1 "September 30, 2004"
.SH NAME
jpegicc - little cms ICC profile applier for JPEG.
.SH SYNOPSIS
.B jpegicc
.RI [ options ] " input.jpg output.jpg"
.SH DESCRIPTION
lcms is a standalone CMM engine, which deals with the color management.
It implements a fast transformation between ICC profiles.
.B jpegicc 
is little cms ICC profile applier for JPEG.
.SH OPTIONS
.TP
.B \-b 
Black point compensation.
.TP 
.B \-c <0,1,2,3>
Precalculates transform. (0=Off, 1=Normal, 2=Hi-res, 3=LoRes) [defaults to 1]
.TP
.B \-g
Marks out-of-gamut colors on softproof.
.TP
.B \-h <0,1,2>
Show summary of options and examples.
.TP
.BI \-i\  profile
Input profile (defaults to sRGB).
.TP
.B \-m <0,1,2,3>
SoftProof intent.
.TP
.B \-n
Ignore embedded profile.
.TP
.BI \-p\  profile
Soft proof profile
.TP
.BI \-o\  profile
.p
Output profile (defaults to sRGB).
.TP
.B \-q <0..100>
Output JPEG quality.
.TP
.B \-t <0,1,2,3>
Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute).
.TP
.B \-v
Verbose.
.SH EXAMPLES
.nf
To color correct from scanner to sRGB:
	jpegicc -iscanner.icm in.jpg out.jpg
	
To convert from monitor1 to monitor2:
	jpegicc -imon1.icm -omon2.icm in.jpg out.jpg

To make a CMYK separation:
	jpegicc -oprinter.icm inrgb.jpg outcmyk.jpg

To recover sRGB from a CMYK separation:
	jpegicc -iprinter.icm incmyk.jpg outrgb.jpg

To convert from CIELab ITU/Fax JPEG to sRGB
	jpegicc -iitufax.icm in.jpg out.jpg
.fi	
.SH NOTES
For suggestions, comments, bug reports etc. send mail to
info@littlecms.com.
.SH SEE ALSO
.BR tifficc (1),
.BR icc2ps (1),
.BR icclink (1),
.BR icctrans (1),
.BR wtpt (1)
.SH AUTHOR
This manual page was written by Shiju p. Nair <shiju.p@gmail.com>,
for the Debian project.
